import { Song, Trophy } from "../types/types";

export const SONGS: Song[] = [
  {
    id: 1,
    title: [
      "Missão: Impossível",
      "Mission: Impossible",
      "Mission Impossible",
      "Missao Impossivel",
    ],
    phrase: "Até correndo o cara é bonito!",
    tip: "De 1996 a 2025, Tom Cruise esteve em todos os 8 filmes da franquia.",
    audio: "/audio/missaoImpossivel.mp3",
  },
  {
    id: 2,
    title: ["Star Wars", "Guerra nas Estrelas", "Guerra das estrelas"],
    phrase: "I am your father!!!",
    tip: "Tem gente que assiste pela ordem cronológica, mas há quem prefira: 1999, 2002, 2005, 1977, 1980 e 1983.",
    audio: "/audio/starwars.mp3",
  },
  {
    id: 3,
    title: ["Harry Potter"],
    phrase: "Lufa-Lufa é a casa mais chata!!!",
    tip: "Avada Kedravra, Expecto Patronum e Wingardium Leviosa são feitiços dessa história.",
    audio: "/audio/harrypotter.mp3",
  },
  {
    id: 4,
    title: [
      "A Pantera Cor-de-Rosa",
      "The Pink Panther",
      "Pink Panther",
      "Pantera Cor-de-Rosa",
      "Pantera cor de Rosa",
    ],
    phrase: "Meu charme já vem com trilha sonora.",
    tip: "Este filme também virou um desenho animado sobre um felino cor-de-rosa.",
    audio: "/audio/pantera.mp3",
  },
  {
    id: 5,
    title: ["Piratas do Caribe", "Pirates of the Caribbean"],
    phrase:
      "'Você é, sem dúvida, o pior pirata de que já ouvi falar.' (Comodoro Norrington)",
    tip: "O personagem principal deste filme é o capitão interpretado por Johnny Depp.",

    audio: "/audio/piratasdocaribe.mp3",
  },
  {
    id: 6,
    title: ["Rocky: Um Lutador", "Rocky"],
    phrase: "De 0 a 10, esse filme é 11.",
    tip: "Um pequeno boxeador recebe uma grande oportunidade. Sylvester Stallone foi o ator principal.",
    audio: "/audio/rocky.mp3",
  },
  {
    id: 7,
    title: [
      "Os Simpsons: O Filme",
      "The Simpsons Movie",
      "The Simpsons",
      "Simpsons",
    ],
    phrase:
      "'A culpa é minha e eu coloco ela em quem eu quiser!' (Homer Simpson)",
    tip: "Este desenho, famoso pelos personagens amarelos, além do filme, estreou na TV em 1987.",
    audio: "/audio/simpsons.mp3",
  },
  {
    id: 8,
    title: ["Titanic", "Titanic"],
    phrase: "Eu sei e você sabe: cabiam os dois ali!!!",
    tip: "Baseado em uma história real, o filme também ficou marcado pela frase: 'Nem Deus pode afundar este navio'.",
    audio: "/audio/titanic.mp3",
  },
  {
    id: 9,
    title: [
      "Três Homens em Conflito",
      "The Good, the Bad and the Ugly",
      "Tres Homens Conflito",
      "O Bom o mau o feio",
      "bom mau o feio",
      "bom mau e o feio",
    ],
    phrase: "Todo mundo já ouviu, mas poucos já viram o filme!",
    tip: "Este filme conta uma história de velho oeste com três homens, cada um com um perfil diferente. Clint Eastwood esteve no elenco.",
    audio: "/audio/treshomensconflito.mp3",
  },
  {
    id: 10,
    title: ["Psicose", "Psycho", "Psicose"],
    phrase: "Você confundiu com Halloween, acertei?",
    tip: "Famoso filme de terror com a clássica cena em preto e branco em que uma mulher é esfaqueada no banheiro.",
    audio: "/audio/psicose.mp3",
  },
  {
    id: 11,
    title: [
      "La La Land: Cantando Estações",
      "La La Land",
      "La la La Land",
      "lalaland",
    ],
    phrase: "Foi só eu que não gostei do final?",
    tip: "Emma Stone e Ryan Gosling estrelam esse drama romântico em estilo musical.",
    audio: "/audio/lalaland.mp3",
  },
  {
    id: 12,
    title: ["Tropa de Elite", "Elite Squad"],
    phrase: "Cadê o baiano?",
    tip: "Este filme mostrou a realidade das favelas e como funciona a elite da polícia do Rio de Janeiro.",
    audio: "/audio/tropaelite.mp3",
  },
  {
    id: 13,
    title: ["O Poderoso Chefão", "The Godfather", "Poderoso Chefão"],
    phrase: "Duvido achar 5 pessoas que já viram todos!",
    tip: "A famosa família Corleone é uma poderosa organização ítalo-americana em Nova York.",
    audio: "/audio/poderosochefao.mp3",
  },
  {
    id: 14,
    title: ["E.T.: O Extraterrestre", "E.T. the Extra-Terrestrial", "ET"],
    phrase: "Dedo com luz!",
    tip: "Steven Spielberg dirigiu essa história sobre a amizade entre um menino e um extraterrestre.",
    audio: "/audio/et.mp3",
  },
  {
    id: 15,
    title: [
      "Superman: O Filme",
      "Superman",
      "Super-Homem",
      "Super Homem",
      "Man Steel",
      "Homem de Aço",
    ],
    phrase: "Sou indestrutível, exceto com uma boa pedrada.",
    tip: "Um dos maiores super-heróis da DC, ele também trabalha como repórter no jornal Planeta Diário, em Metrópolis.",
    audio: "/audio/superma.mp3",
  },
  {
    id: 16,
    title: [
      "O Auto da Compadecida",
      "A Dog's Will",
      "Auto da Compadecida",
      "Dog will",
      "A dogs will",
    ],
    phrase: "Não sei?! Só sei que foi assim!",
    tip: "Ariano Suassuna foi o escritor desta obra que conta com os personagens João Grilo e Chicó.",
    audio: "/audio/autocompad.mp3",
  },
  {
    id: 17,
    title: [
      "A Lista de Schindler",
      "Schindler's List",
      "Lista de Schindler",
      "shindlers list",
    ],
    phrase: "Escorreu uma lágrima aqui.",
    tip: "Conta a história nua e crua da Segunda Guerra Mundial e como o alemão Oskar ____ salvou centenas de judeus.",
    audio: "/audio/listashindler.mp3",
  },
  {
    id: 18,
    title: [
      "Batman: O Cavaleiro das Trevas",
      "The Dark Knight",
      "Cavaleiro das Trevas",
      "Dark Knight",
      "Batman",
    ],
    phrase: "Se você for rico, você pode ser um super-herói... ou não!",
    tip: "Para muitos, esta foi a melhor trilogia do herói mascarado. Christopher Nolan foi o diretor.",
    audio: "/audio/batmandarkknight.mp3",
  },
  {
    id: 19,
    title: ["Ben-Hur", "Ben Hur", "benhur"],
    phrase: "O primeiro filme com 11 Oscars.",
    tip: "Este filme, lançado em 1959, foi o primeiro a ganhar 11 Oscars. Depois dele, isso só voltou a acontecer em 1997.",
    audio: "/audio/benhur.mp3",
  },
  {
    id: 20,
    title: [
      "O Fabuloso Destino de Amélie Poulain",
      "Le Fabuleux Destin d'Amélie Poulain",
      "Amélie",
      "Amelie",
      "Amelie Poulain",
    ],
    phrase: "A vida é bela, apesar de tudo.",
    tip: "Clássico francês que conta a história de uma moça que encontra uma caixinha em seu apartamento e decide achar o dono.",
    audio: "/audio/ameliepolan.mp3",
  },
  {
    id: 21,
    title: [
      "Carruagens de Fogo",
      "Chariots of Fire",
      "Carruagem de Fogo",
      "carruagem fogo",
    ],
    phrase: "Uma música que saiu do filme para a glória.",
    tip: "Este drama de 1981 conta a história de dois atletas com crenças diferentes competindo nas Olimpíadas de 1924.",
    audio: "/audio/carruagemfogo.mp3",
  },
  {
    id: 22,
    title: [
      "De Volta para o Futuro",
      "Back to the Future",
      "Volta para o Futuro",
    ],
    phrase: "Cadê os skates voadores de 2025?",
    tip: "Um professor maluco faz um experimento malsucedido e um adolescente viaja para o passado.",
    audio: "/audio/devoltafuturo.mp3",
  },
  {
    id: 23,
    title: ["Divertidamente", "Inside Out", "Divertidamente", "insideout"],
    phrase: "Bing Bong, Bing Bong meu amigo para brincar...",
    tip: "Esta animação foi elogiado por ensinar inteligência emocional ao mostrar as emoções como personagens.",
    audio: "/audio/divertidamente.mp3",
  },
  {
    id: 24,
    title: [
      "Forrest Gump: O Contador de Histórias",
      "Forrest Gump",
      "O contador de historia",
    ],
    phrase: "Run, Forrest, RUUUNNN!!!",
    tip: "Mesmo sendo ingênuo, o personagem vivido por Tom Hanks contou histórias sentado em um ponto de ônibus.",
    audio: "/audio/forrestgump.mp3",
  },
  {
    id: 25,
    title: ["Gladiador", "Gladiator"],
    phrase: "Maximus Decimus Meridius!!!",
    tip: "Um general romano amado pelo povo e pelo imperador luta por sua vida até ter a oportunidade de desafiar o filho do imperador.",
    audio: "/audio/gladiador.mp3",
  },
  {
    id: 26,
    title: ["A Origem", "Inception", "Origem"],
    phrase: "A vida onde os ricos dormem.",
    tip: "Christopher Nolan dirigiu essa trama em que ideias são 'plantadas' através dos sonhos das pessoas.",
    audio: "/audio/inception.mp3",
  },
  {
    id: 27,
    title: [
      "Indiana Jones e os Caçadores da Arca Perdida",
      "Raiders of the Lost Ark",
      "Indiana Jones",
      "Indianna Jones",
      "Cacadores da Arca Perdida",
    ],
    phrase: "Sem ele, a história aconteceria do mesmo jeito que aconteceu?",
    tip: "Criado por George Lucas e Steven Spielberg, o filme acompanha as aventuras do arqueólogo Henry Walton ____ Jones Jr.",
    audio: "/audio/indianajones.mp3",
  },
  {
    id: 28,
    title: ["Interestelar", "Interstellar", "Interstelar", "Estelar"],
    phrase: "Aconteceu o mesmo desastre climático nos EUA em 1930.",
    tip: "Os astronautas recebem a missão de verificar possíveis planetas para abrigar a população mundial.",
    audio: "/audio/interstellar.mp3",
  },
  {
    id: 29,
    title: [
      "Jurassic Park: Parque dos Dinossauros",
      "Jurassic Park",
      "Parque dos Dinossauros",
      "parque dinossauros",
      "jurassico",
    ],
    phrase: "Rã + Mosquito = Tiranossauro?",
    tip: "Nessa história, paleontólogos conseguem reviver dinossauros a partir de DNA encontrado em mosquitos.",
    audio: "/audio/jurassicpark.mp3",
  },
  {
    id: 30,
    title: ["Cidade de Deus", "City of God", "Cidade Deus"],
    phrase: "Pega a galinha aí, cumpade!!!",
    tip: "Buscapé cresce em um universo de muita violência e conhece pessoas como Dadinho, que se torna Zé Pequeno quando adulto.",
    audio: "/audio/cidadedeus.mp3",
  },
  {
    id: 31,
    title: [
      "E o Vento Levou",
      "Gone with the Wind",
      "O vento levou",
      "Vento Levou",
    ],
    phrase: "Filme a cores mais velho que a vó.",
    tip: "O filme de 1939 conquistou 10 Oscars e conta a história de Scarlett O'Hara, que consegue tudo o que quer, exceto o amor de Ashley Wilkes.",
    audio: "/audio/oventolevou.mp3",
  },
  {
    id: 32,
    title: [
      "A Ponte do Rio Kwai",
      "The Bridge on the River Kwai",
      "Ponte do Rio Kwai",
      "Ponte Rio Kwai",
    ],
    phrase: "Se você é velho, você lembra do Faustão.",
    tip: "Prisioneiros de guerra são forçados a construir uma ponte para ajudar seus inimigos neste filme vencedor de 7 Oscars.",
    audio: "/audio/ponteriokwai.mp3",
  },
  {
    id: 33,
    title: [
      "O Último dos Moicanos",
      "The Last of the Mohicans",
      "Último dos Moicanos",
      "Mohicans",
      "Moicanos",
    ],
    phrase: "Daqui surgiu a expressão 'ser o último dos moicanos'.",
    tip: "Durante a guerra entre franceses e ingleses na América do Norte, um homem branco criado por indígenas tenta defender sua tribo.",
    audio: "/audio/ultiimodosmoicanos.mp3",
  },
  {
    id: 34,
    title: ["Up: Altas Aventuras", "Up", "Altas Aventuras"],
    phrase:
      "'Sr. Wilson?' ou 'Cachorro idiota', de qual frase você se lembra mais?",
    tip: "Um vendedor de balões, prestes a perder sua casa, decide voar com ela até a América do Sul.",
    audio: "/audio/up.mp3",
  },
  {
    id: 35,
    title: [
      "A Vida é Bela",
      "La Vita è Bella",
      "Life is Beautiful",
      "Vida é Bela",
    ],
    phrase: "Buongiorno Principessa.",
    tip: "Este filme ganhou o Oscar de Melhor Filme Estrangeiro, superando o aclamado brasileiro Central do Brasil.",
    audio: "/audio/vidaebela.mp3",
  },
  {
    id: 36,
    title: ["Os Vingadores", "The Avengers", "Vingadores", "Avengers"],
    phrase: "Vingadores... Avante!",
    tip: "A maior reunião de heróis da Marvel forma a equipe que dá nome ao filme.",
    audio: "/audio/vingadores.mp3",
  },
  {
    id: 37,
    title: ["Tubarão", "Jaws", "Tubarao", "Shark"],
    phrase:
      "Se você tem mais de 35 anos, definitivamente tinha medo de tubarão na praia!",
    tip: "Som, montagem e trilha sonora renderam 3 Oscars a este filme sobre um animal que fez banhistas terem medo das praias.",
    audio: "/audio/tubarao.mp3",
  },
  {
    id: 38,
    title: ["007", "James Bond", "Bond"],
    phrase: "O agente só ficou loiro em 2005.",
    tip: "O mais famoso agente secreto do cinema foi criado em 1953 por Ian Fleming.",
    audio: "/audio/007.mp3",
  },
  {
    id: 39,
    title: [
      "Meu Tio Matou um Cara",
      "My Uncle Killed a Guy",
      "Tio matou um cara",
    ],
    phrase: "Spoiler: ele não matou um cara.",
    tip: "Com o tio preso por supostamente matar uma pessoa, o sobrinho junta provas de que não foi isso que aconteceu.",
    audio: "/audio/sorayaqueima.mp3",
  },
  {
    id: 40,
    title: [
      "Kung Fu Panda",
      "Kung Fu Panda's",
      "Kung Fu Pandas",
      "kungfu panda",
    ],
    phrase: "...e é por isso que se chama presente!",
    tip: "Uma animação que retrata a filosofia e a história do kung fu.",
    audio: "/audio/kongfupanda.mp3",
  },
  {
    id: 41,
    title: [
      "Velozes e Furiosos",
      "The Fast and the Furious",
      "Fast and Furious",
      "Desafio em Tokio",
    ],
    phrase: "Era corrida de carros e agora é o quê?",
    tip: "Iniciada em 2001, a saga retratava corridas clandestinas, assaltos e a importância da família.",
    audio: "/audio/velozesfuriosos.mp3",
  },
  {
    id: 42,
    title: ["Transformers", "Transformers", "Trans formers"],
    phrase: "A trilha sonora era boa, mas a música do meme é sensacional.",
    tip: "Robôs de outros planetas possuem a capacidade de se transformar em qualquer máquina da Terra.",
    audio: "/audio/transformers.mp3",
  },
  {
    id: 43,
    title: ["Toy Story", "Toy Story"],
    phrase: "O garfinho foi animado por um brasileiro.",
    tip: "Conta a história do que acontece com os brinquedos quando não estamos olhando para eles.",
    audio: "/audio/toystory.mp3",
  },
  {
    id: 44,
    title: ["Top Gun: Ases Indomáveis", "Top Gun", "Ases Indomáveis"],
    phrase: "Homens bombados, óculos de sol, avião e vôlei na praia de jeans.",
    tip: "Retrata a escola naval de pilotos de caça dos Estados Unidos.",
    audio: "/audio/topgun.mp3",
  },
  {
    id: 45,
    title: [
      "O Senhor dos Anéis",
      "The Lord of the Rings",
      "Lord of the Rings",
      "Senhor dos Aneis",
    ],
    phrase:
      "'Tudo o que temos de decidir é o que fazer com o tempo que nos é dado.' (Gandalf)",
    tip: "A franquia acumula 17 Oscars, e o capítulo final sozinho venceu 11 estatuetas.",
    audio: "/audio/senhoraneis.mp3",
  },
  {
    id: 46,
    title: [
      "Réquiem para um Sonho",
      "Requiem for a Dream",
      "Réquiem para um sonho",
    ],
    phrase: "Crianças, não usem drogas!",
    tip: "Um terror psicológico que mostra a relação das pessoas com seus vícios.",
    audio: "/audio/requiemDream.mp3",
  },
  {
    id: 47,
    title: ["Mortal Kombat", "Mortal Kombat", "Combate Mortal"],
    phrase: "Sub-Zero, Sub-Zero, eu escolhia o Sub-Zero.",
    tip: "Sucesso dos games também retratado no cinema. Em 1992, o jogo usou atores reais para dar vida aos personagens.",
    audio: "/audio/mk.mp3",
  },
  {
    id: 48,
    title: ["Madagascar", "Madagascar", "Madagaskar"],
    phrase: "Eu sei que você cantou quando ouviu!",
    tip: "Um grupo de animais foge do zoológico de Nova York e acaba chegando ao continente africano.",
    audio: "/audio/madagascar.mp3",
  },
  {
    id: 49,
    title: ["Kill Bill", "Kill Bill", "KillBill"],
    phrase: "Tarantino arrasou neste!",
    tip: "Uma ex-assassina, conhecida apenas como Noiva, acorda de um coma de quatro anos decidida a se vingar de ____.",
    audio: "/audio/killbill.mp3",
  },
  {
    id: 50,
    title: ["Homem de Ferro", "Iron Man", "Ironman"],
    phrase: "Playboy, filantropo, bilionário e Homem de Ferro.",
    tip: "Um dos principais personagens da Marvel nos cinemas foi interpretado por Robert Downey Jr.",
    audio: "/audio/ironman.mp3",
  },
  {
    id: 51,
    title: [
      "Intocáveis",
      "The Intouchables",
      "Intouchables",
      "Intocáveis",
      "Intouchables",
      "Untouchable",
    ],
    phrase: "Ele é forte, troca minhas meias e não tem pena.",
    tip: "Um milionário tetraplégico contrata um homem da periferia para ser seu acompanhante, e os dois criam uma grande amizade.",
    audio: "/audio/intocaveis.mp3",
  },
  {
    id: 52,
    title: ["Frozen: Uma Aventura Congelante", "Frozen", "Frozen", "lerigo"],
    phrase: "Eu sei que você também cantou essa!",
    tip: "Esse sucesso da Disney conta a história da Rainha da Neve.",
    audio: "/audio/frozen.mp3",
  },
  {
    id: 53,
    title: ["Footloose", "Footloose", "Footloose"],
    phrase:
      "Ainda vigorava a lei em 1980 na cidade de Elmore, Oklahoma, onde era proibido dançar.",
    tip: "Ren McCormack descobre que a cidade do interior para a qual se mudou possui uma lei que proíbe dança e música pop.",
    audio: "/audio/footloose.mp3",
  },
  {
    id: 54,
    title: ["Flashdance", "Flashdance", "Flash Dance"],
    phrase: "A dança da cadeira e balde de água na cabeça.",
    tip: "Cheio de cenas coreografadas, o filme lembra uma versão moderna da Cinderela, sobre uma operária que sonha em ser bailarina.",
    audio: "/audio/flashdance.mp3",
  },
  {
    id: 55,
    title: ["O Exorcista", "The Exorcist", "Exorcist", "Exorcista"],
    phrase: "Rodou a cabeça!",
    tip: "A produção deste clássico do terror foi cercada de acontecimentos bizarros, de incêndios no set a mortes no elenco.",
    audio: "/audio/exorcista.mp3",
  },
  {
    id: 56,
    title: [
      "Os Embalos de Sábado à Noite",
      "Saturday Night Fever",
      "Embalos de Sábado a noite",
      "Febre de Sábado à Noite",
    ],
    phrase: "O filme onde eternizou o disco dance!",
    tip: "Esse clássico musical foi estrelado por John Travolta em 1977 e imortalizou o estilo disco.",
    audio: "/audio/embalossabado.mp3",
  },
  {
    id: 57,
    title: [
      "2 Filhos de Francisco",
      "2 Filhos de Francisco",
      "Dois Filhos de Francisco",
      "Filhos de francisco",
    ],
    phrase: "Já tomou seu ovo cru hoje?",
    tip: "Clássico filme brasileiro que conta a história da dupla sertaneja Zezé Di Camargo & Luciano.",
    audio: "/audio/doisfilhofrancisco.mp3",
  },
  {
    id: 58,
    title: ["Dirty Dancing", "Dirty Dancing", "Dirty Dancing"],
    phrase: "Sempre tem acidentes em casamentos quando toca essa música.",
    tip: "Primeiro filme a vender 1 milhão de cópias em VHS, foi protagonizado por Patrick Swayze e Jennifer Grey.",
    audio: "/audio/dirtydancing.mp3",
  },
  {
    id: 59,
    title: ["Deadpool", "Deadpool", "Deadpool"],
    phrase: "Bye bye bye também é boa, mas essa aqui é a cara dele!",
    tip: "Alter ego de Wade Winston Wilson, esse anti-herói tem a capacidade de quebrar a quarta parede.",
    audio: "/audio/deadpool.mp3",
  },
  {
    id: 60,
    title: ["Crepúsculo", "Twilight", "Crepusculo"],
    phrase: "Você é time livro ou time filme?",
    tip: "Uma estudante conhece um belo e misterioso adolescente, que também é um vampiro.",
    audio: "/audio/crepusculo.mp3",
  },
  {
    id: 61,
    title: ["Blade: O Caçador de Vampiros", "Blade", "Blade"],
    phrase: "Merece um crossover com Crepúsculo?",
    tip: "Um anti-herói da Marvel com força sobre-humana dedicado à caça de vampiros.",
    audio: "/audio/blade.mp3",
  },
  {
    id: 62,
    title: [
      "2001: Uma Odisseia no Espaço",
      "2001: A Space Odyssey",
      "2001",
      "Odisseia no espaco",
    ],
    phrase: "IA e evolução humana debatidos em 1968.",
    tip: "Esse clássico da ficção científica sugere que a evolução da humanidade foi impulsionada por forças superiores, os misteriosos monólitos.",
    audio: "/audio/2001.mp3",
  },
  {
    id: 63,
    title: ["Os Caça-Fantasmas", "caca fantasmas", "Ghostbusters"],
    phrase:
      "Um filme onde fantasmas que ultrapassam paredes são presos em caixa de metal.",
    tip: "Eles são parapsicólogos que decidem abrir uma empresa especializada em capturar fantasmas.",
    audio: "/audio/cacafantasmas.mp3",
  },
  {
    id: 64,
    title: ["Whiplash", "Wiplach", "uiplash"],
    phrase: "We will rock you seria muito fácil para ele.",
    tip: "Um maestro extremamente exigente e um baterista em busca da perfeição musical.",
    audio: "/audio/whiplash.mp3",
  },
  {
    id: 65,
    title: ["Um ninja da pesada", "Beverly Hills Ninja", "Ninja da pesada"],
    phrase: "A lenda do ninja branco? Alguns dizem que sou eu.",
    tip: "Um garoto branco e obeso é treinado nas artes do ninjutsu e, mesmo sendo desajeitado, se torna um verdadeiro ninja.",
    audio: "/audio/umninjapesada.mp3",
  },
  {
    id: 66,
    title: ["Pulp Fiction: Tempo de Violência", "pulp fiction"],
    phrase: "Três histórias e muita violência ao estilo Tarantino.",
    tip: "John Travolta, Samuel L. Jackson, Uma Thurman e Bruce Willis fazem parte do elenco deste clássico de Tarantino.",
    audio: "/audio/pulpfiction.mp3",
  },
  {
    id: 67,
    title: [
      "Monstros S.A.",
      "Monsters, Inc.",
      "Monsters Inc",
      "Monstros SA",
      "Monster Inc",
    ],
    phrase:
      "A Boo provou que quando não temos medo, nosso medo tem medo da gente.",
    tip: "Nosso negócio é assustar crianças em seus quartos para gerar energia.",
    audio: "/audio/mostrossa.mp3",
  },
  {
    id: 68,
    title: ["Matrix"],
    phrase: "E você qual pílula tomaria, a vermelha ou a azul?",
    tip: "Um mundo em que humanos vivem conectados por cabos e precisam desconfiar da realidade para se libertar.",
    audio: "/audio/matrix.mp3",
  },
  {
    id: 69,
    title: [
      "Halloween",
      "Noite do Terror",
      "Helloween",
      "Helowen",
      "Michael Myers",
    ],
    phrase: "O som parece Psicose, mas não é, parece Exorcista, mas não é!",
    tip: "Michael Myers é o assassino por trás deste clássico do Dia das Bruxas.",
    audio: "/audio/halloween.mp3",
  },
  {
    id: 70,
    title: ["Ghost: Do Outro Lado da Vida", "Ghost", "Do outro lado da vida."],
    phrase:
      "Um dos beijos mais famosos do cinema... o beijo que ninguem sente.",
    tip: "Após morrer, ele descobre que sua namorada corre perigo e procura uma médium para ajudá-la.",
    audio: "/audio/ghost.mp3",
  },
  {
    id: 71,
    title: [
      "A Família Addams",
      "The Addams Family",
      "Familia Addams",
      "Familia Adams",
      "Addams Family",
    ],
    phrase: "Se você chutou Wandinha você tem menos de 25 anos.",
    tip: "Wandinha faz parte desta família junto com Tio Chico, Mortícia, Gomez e outros personagens.",
    audio: "/audio/familiaadams.mp3",
  },
  {
    id: 72,
    title: ["Esqueceram de mim", "Home Alone"],
    phrase:
      "Kevin provando que cuida melhor de uma casa do que muito adulto por ai.",
    tip: "Um menino cria armadilhas contra dois ladrões enquanto sua família viaja e o esquece sozinho no Natal.",
    audio: "/audio/esquecerammim.mp3",
  },
  {
    id: 73,
    title: ["A Era do Gelo", "Ice Age", "Era do Gelo"],
    phrase: "A gente vai viver... a gente vai morrer!",
    tip: "Um mamute, um tigre-dentes-de-sabre e uma preguiça formam o trio principal desta animação.",
    audio: "/audio/eragelo.mp3",
  },
  {
    id: 74,
    title: ["Clube da Luta", "Fight Club", "Clube de Combate"],
    phrase: "Regra nº 1 do clube da luta: ",
    tip: "Desiludido com o mundo corporativo, um homem conhece um amigo misterioso e cria um clube secreto.",
    audio: "/audio/clubeluta.mp3",
  },
  {
    id: 75,
    title: ["Armageddon", "Armaggedon", "Armagedon", "Armagedom"],
    phrase:
      "Treinar astronautas para perfurar uma pedra ou treinar perfuradores para virar astronauta? ",
    tip: "Um asteroide vai colidir com a Terra, e a solução é colocar uma bomba nuclear dentro dele.",
    audio: "/audio/armageddon.mp3",
  },
  {
    id: 76,
    title: [
      "Aladdin",
      "Aladin",
      "Aladim",
      "Aladdim",
      "Alladdim",
      "Alladim",
      "Alladin",
    ],
    phrase: "Você tem direito a um desejo... Desejo ter desejos infinitos.",
    tip: "Um jovem pobre, uma princesa comprometida, um gênio da lâmpada e o macaquinho Abu fazem parte desta animação.",
    audio: "/audio/aladin.mp3",
  },
  {
    id: 77,
    title: ["As Branquelas", "Branquelas", "White Chicks"],
    phrase: "Segura aqui o meu poodle!!!",
    tip: "Dois policiais negros se infiltram na elite vestidos como duas mulheres loiras.",
    audio: "/audio/branquelas.mp3",
  },
  {
    id: 78,
    title: [
      "Coração de Cavaleiro",
      "A Knight's Tale",
      "knights tale",
      "coracao cavaleiro",
    ],
    phrase: "Você pode ser o que você sonha ser.",
    tip: "Um jovem camponês e seus amigos entram para a elite dos torneios de cavalaria na era medieval.",
    audio: "/audio/coracaocavaleiro.mp3",
  },
  {
    id: 79,
    title: ["Shrek", "Scherek", "Schereke", "Schrek", "sherek"],
    phrase: "Nunca julgue pela aparencia, ele pode ser feio verde e gordo.",
    tip: "Ele vive em um pântano e não quer ser incomodado, mas um burro falante muda sua vida.",
    audio: "/audio/schrek.mp3",
  },
  {
    id: 80,
    title: [
      "O Mágico de OZ",
      "The Wizard of Oz",
      "Magico de OZ",
      "magico oz",
      "oz",
    ],
    phrase: "Tudo aquilo que buscamos podemos encontrar dentro de nós.",
    tip: "Um espantalho sem cérebro, um homem de lata sem coração e um leão medroso acompanham Dorothy nessa história.",
    audio: "/audio/magicodeoz.mp3",
  },
  {
    id: 81,
    title: [
      "MIB - Homens de Preto",
      "Men in Black",
      "Homens de Preto",
      "Men is Black",
      "MIB",
    ],
    phrase: "How let the dogs out!?",
    tip: "Dois agentes de uma organização secreta protegem a Terra de ameaças alienígenas.",
    audio: "/audio/mib.mp3",
  },
  {
    id: 82,
    title: ["O Rei Leão", "The Lion King", "Rei Leão", "Lion King"],
    phrase: "Look, thats a lion, Oh my God!",
    tip: "Após a morte de seu pai, Mufasa, armada pelo tio Scar, ele foge e retorna anos depois para recuperar o trono.",
    audio: "/audio/reileao.mp3",
  },
  {
    id: 83,
    title: ["O Máskara", "Maskara", "Máscara", "The Mask", "Mask"],
    phrase: "Demais!!!",
    tip: "Interpretado por Jim Carrey, o personagem ganhou vida nos cinemas com seu rosto verde, sorriso exagerado e terno amarelo.",
    audio: "/audio/maskara.mp3",
  },
  {
    id: 84,
    title: ["Homem-Aranha", "Spider Man", "Spider-Man", "Homem Aranha"],
    phrase: "'Com grandes poderes vem grandes responsabilidades.' (Tio Ben)",
    tip: "O herói mascarado que não voa, mas escala paredes e atravessa os prédios de Nova York como um Tarzan urbano.",
    audio: "/audio/homemaranha.mp3",
  },
  {
    id: 85,
    title: ["Jogos Mortais", "Saw", "Jigsaw"],
    phrase:
      "O Chester do Linkin Park, foi ator no sétimo filme por causa dos seus gritos marcantes.",
    tip: "Este filme de terror mostra participantes presos em jogos, onde precisam fazer sacrifícios para sobreviver.",
    audio: "/audio/jogosmortais.mp3",
  },
  {
    id: 86,
    title: ["Uma Linda Mulher", "Pretty Woman", "Linda Mulher"],
    phrase:
      "O que era para ser um drama sombrio virou um dos filmes mais românticos da decada de 1990.",
    tip: "O que seria um drama sombrio acabou se tornando um dos romances mais famosos da década de 1990.",
    audio: "/audio/lindamulher.mp3",
  },
  {
    id: 87,
    title: ["High School Musical", "HSM", "Hight School Musical"],
    phrase: "Aquele musical da Disney que ninguém esquece.",
    tip: "Adolescentes do ensino médio cantam e dançam o tempo todo neste musical da Disney.",
    audio: "/audio/highschoolmusical.mp3",
  },
  {
    id: 88,
    title: ["Duna", "Dune"],
    phrase: "Para fungir é bom saber andar na areia simulando o vento.",
    tip: "Uma das maiores obras da ficção científica, escrita originalmente em 1965, ganhou remake na década de 2020.",
    audio: "/audio/duna.mp3",
  },
  {
    id: 89,
    title: [
      "Curtindo a Vida Adoidado",
      "Ferris Bueller's Day Off",
      "Ferris Bueller",
      "Curtindo a Vida",
    ],
    phrase: "Colocar o carro no macaco e dar a ré para voltar a quilometragem.",
    tip: "Um adolescente mata aula e participa de um desfile enquanto é perseguido pelo diretor da escola.",
    audio: "/audio/curtindoavida.mp3",
  },
  {
    id: 90,
    title: [
      "O Guarda-Costas",
      "O guarda costas",
      "guarda costas",
      "The Bodyguard",
      "Guarda-Costas",
      "Bodyguard",
    ],
    phrase: "E tem gente que confunde com titanic essa trilha.",
    tip: "Um ex-agente secreto é contratado para proteger uma cantora e acaba se envolvendo romanticamente com ela.",
    audio: "/audio/guaradcostas.mp3",
  },
  {
    id: 91,
    title: ["Avatar"],
    phrase: "E aqui nós somos os vilões!",
    tip: "Em busca de recursos naturais, os humanos descobrem um planeta habitado por criaturas humanoides azuis.",
    audio: "/audio/avatar.mp3",
  },
  {
    id: 92,
    title: ["300", "Trezentos", "Three hundred"],
    phrase: "Spartaaa?! RAUUUULLLL, RAUUUL RAUUULL!!!!",
    tip: "Uma pequena tropa espartana enfrenta centenas de milhares de persas.",
    audio: "/audio/trezentos.mp3",
  },
  {
    id: 93,
    title: ["Escola de Rock", "School of Rock", "Escola Rock", "Rock School"],
    phrase: "Jack Black é show!!!",
    tip: "Jack Black vira professor substituto, mas seu verdadeiro objetivo é montar uma banda de rock.",
    audio: "/audio/escolarock.mp3",
  },
  {
    id: 94,
    title: [
      "Como Treinar o Seu Dragão",
      "How to Train Your Dragon",
      "Treinar Seu Dragão",
      "Treinar Dragão",
      "Como treinar seu Dragão",
    ],
    phrase:
      "Ele não tem um pedaço da perna e o outro uma parte do rabo mas juntos eles podem voar.",
    tip: "Um jovem viking muda a realidade de sua tribo ao descobrir que dragões podem ser domados, e não apenas caçados.",
    audio: "/audio/treinardragao.mp3",
  },
  {
    id: 95,
    title: [
      "Jogos Vorazes",
      "The Hunger Games",
      "Hunger Games",
      "Jogos da fome",
    ],
    phrase: "Que a sorte esteja sempre a favor de você.",
    tip: "Em um futuro distópico, jovens são obrigados a lutar entre si em um evento televisionado.",
    audio: "/audio/jogosvorazes.mp3",
  },
  {
    id: 96,
    title: [
      "Cantando na Chuva",
      "Singin' in the Rain",
      "Singing in the rain",
      "Dancando na Chuva",
    ],
    phrase:
      "Não possui nenhum oscar mas é considerado um dos maiores musicais de todos os tempos.",
    tip: "Esse filme de 1952 tem a famosa cena em que Gene Kelly canta enqunato dança na chuva.",
    audio: "/audio/singinrain.mp3",
  },
  {
    id: 97,
    title: ["Mulher Maravilha", "Wonder Woman"],
    phrase:
      "William Moulton Marston co-inventor do detector de mentiras também criou a personagem.",
    tip: "A heroína da DC, dona do Laço da Verdade, é filha de Zeus e Hipólita.",
    audio: "/audio/mulhermaravilha.mp3",
  },
  {
    id: 98,
    title: ["Loucademia de Polícia", "Police Academy", "Academia de polícia"],
    phrase:
      "Michael Winslow, o beatboxer que reproduzia quase todos os sons com a boca.",
    tip: "Foram 7 filmes em 10 anos. Essa comédia policial esteve nos cinemas entre 1984 e 1994.",
    audio: "/audio/loucademiapolicia.mp3",
  },
  {
    id: 99,
    title: ["Os Incríveis", "The Incredibles", "Incríveis", "Incredibles"],
    phrase: "Você pode ser a inspiração de um vilão, mesmo sem querer.",
    tip: "Ele é herói, a esposa também, e os três filhos possuem habilidades especiais nesta incrível animação.",
    audio: "/audio/incriveis.mp3",
  },
  {
    id: 100,
    title: [
      "O Quinto Elemento",
      "The Fifth Element",
      "Quinto Elemento",
      "Fifth Element",
    ],
    phrase: "Filme francês, que fala inglês com atores dos EUA.",
    tip: "No século 23, um taxista precisa proteger o 'quinto elemento', capaz de salvar a Terra.",
    audio: "/audio/quintoelemento.mp3",
  },
  {
    id: 101,
    title: [
      "As Panteras: Detonando",
      "Charlie's Angels: Full Throttle",
      "As Panteras",
      "Panteras Detonando",
      "Panteras",
      "Charlie's Angels",
      "Charlies Angels",
    ],
    phrase: "Rodrigo Santoro aparece no 2.",
    tip: "Elas não usam armas, mas são incríveis. Assim como em Três Espiãs Demais, também recebem ordens de um chefe chamado Jerry.",
    audio: "/audio/aspanterasdetonando.mp3",
  },
  {
    id: 102,
    title: ["Motoqueiro Fantasma", "Ghost Rider", "Cavaleiro Fantasma"],
    phrase:
      "Mais um personagem que não aprendeu que não se deve vender a alma para o diabo.",
    tip: "Johnny Blaze, personagem de Nicolas Cage, ganha poderes sobrenaturais e assume a forma de uma caveira flamejante.",
    audio: "/audio/ghostrider.mp3",
  },
];

// Crie um brasão cartunesco com um pequeno abajur articulado de mesa, com corpo metálico e design minimalista no formato de jogos online, no estilo da imagem de referência com o fundo completamente branco e o texto "Fanáticos das Animações"
// Crie um brasão cartunesco com a cabeca de hans zimmer no formato de jogos online, no estilo da imagem de referência om o fundo completamente branco
export const TROPHIES: Trophy[] = [
  {
    id: "steven",
    name: "Steven Spielberg",
    image: "/images/steventrophy.png",
    required: [14, 17, 27, 29, 37],
    colors: {
      bg: "#fef9c3",
      bgD: "#3a2e00",
      border: "#eab308",
      glow: "#facc15",
      text: "#78350f",
    },
  },
  {
    id: "hans",
    name: "Hans Zimmer",
    image: "/images/hansZImmer.png",
    required: [5, 18, 25, 26, 28, 40, 82, 88],
    colors: {
      bg: "#e0f2fe",
      bgD: "#0c2a4a",
      border: "#0ea5e9",
      glow: "#38bdf8",
      text: "#0c4a6e",
    },
  },
  {
    id: "brazuka",
    name: "Cinema Brazuka",
    image: "/images/brazuka.png",
    required: [12, 16, 30, 39, 57],
    colors: {
      bg: "#fff7ed",
      bgD: "#2a1000",
      border: "#f97316",
      glow: "#fb923c",
      text: "#7c2d12",
    },
  },
  {
    id: "johnW",
    name: "John Williams",
    image: "/images/johnwillians.png",
    required: [2, 3, 14, 15, 27, 29, 37, 72],
    colors: {
      bg: "#f3e8ff",
      bgD: "#2a1040",
      border: "#a855f7",
      glow: "#c084fc",
      text: "#581c87",
    },
  },
  {
    id: "oldbutgold",
    name: "Old but Gold - Filmes com mais de 60 anos",
    image: "/images/oldButGold.png",
    required: [4, 9, 10, 19, 31, 32, 80, 96],
    colors: {
      bg: "#dcfce7",
      bgD: "#0a2010",
      border: "#22c55e",
      glow: "#4ade80",
      text: "#14532d",
    },
  },
  {
    id: "animations",
    name: "Fanáticos das Animações",
    image: "/images/animations.png",
    required: [23, 34, 40, 43, 48, 52, 67, 73, 76, 79, 82, 94, 99],
    colors: {
      bg: "#fef9c3",
      bgD: "#2a2000",
      border: "#eab308",
      glow: "#facc15",
      text: "#1e3a8a",
    },
  },
  {
    id: "winners",
    name: "10 ou mais Oscars",
    image: "/images/titanic.png",
    required: [8, 19, 31, 45],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "heroes",
    name: "Mestres dos Super-Heróis",
    image: "/images/superherois.png",
    required: [15, 18, 36, 50, 59, 61, 84, 97, 102],
    colors: {
      bg: "#fff7ed",
      bgD: "#2a1000",
      border: "#f97316",
      glow: "#fb923c",
      text: "#7c2d12",
    },
  },
  {
    id: "dance",
    name: "Dance Dance Dance",
    image: "/images/dancedancedance.png",
    required: [11, 53, 54, 56, 58, 87, 96],
    colors: {
      bg: "#fff7ed",
      bgD: "#2a1000",
      border: "#f97316",
      glow: "#fb923c",
      text: "#7c2d12",
    },
  },
  {
    id: "horror",
    name: "Horror Story",
    image: "/images/horrorstory.png",
    required: [10, 46, 55, 69, 85],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "tickets",
    name: "Maiores Bilheterias",
    image: "/images/maioresbilheterias.png",
    required: [3, 8, 18, 29, 36, 45, 91],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "fiction",
    name: "Aficionados por Ficção",
    image: "/images/aficionadosficcao1.png",
    required: [2, 14, 22, 26, 28, 29, 62, 68, 75, 81, 100],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "goldenage",
    name: "BlockBusters: 70s - 90s",
    image: "/images/eradeouromoderna.png",
    required: [2, 6, 13, 14, 15, 27, 37, 44, 55, 63, 69, 70, 72, 86, 89],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "news",
    name: "Recentes Memoraveis",
    image: "/images/recentesmemoraveis.png",
    required: [11, 23, 26, 28, 36, 51, 52, 59, 64, 88, 94, 95, 97],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "cryforme",
    name: "Crise Existencial",
    image: "/images/criseexistencial.png",
    required: [17, 30, 35, 46, 51, 62, 74],
    colors: {
      bg: "#fee2e2",
      bgD: "#3a0a0a",
      border: "#ef4444",
      glow: "#f87171",
      text: "#7f1d1d",
    },
  },
  {
    id: "books",
    name: "Grandes Adaptações Literárias",
    image: "/images/booksandmovies.png",
    required: [3, 13, 17, 24, 29, 31, 33, 45, 55, 60, 88, 95],
    colors: {
      bg: "#fef9c3",
      bgD: "#3a2e00",
      border: "#eab308",
      glow: "#facc15",
      text: "#78350f",
    },
  },
  {
    id: "master",
    name: "Master Movie",
    image: "/images/mastermovie.png",
    required: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
      76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
      94, 95, 96, 97, 98, 99, 100, 101, 102,
    ],
    colors: {
      bg: "#f3e8ff",
      bgD: "#2a1040",
      border: "#a855f7",
      glow: "#c084fc",
      text: "#581c87",
    },
  },
];
